# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_2(object):
    def setupUi(self, delete_2):
        delete_2.setObjectName("delete_2")
        delete_2.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(delete_2)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ID.setGeometry(QtCore.QRect(150, 130, 71, 22))
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(70, 30, 121, 28))
        self.pushButton_search.setObjectName("pushButton_search")
        self.label_ID = QtWidgets.QLabel(self.centralwidget)
        self.label_ID.setGeometry(QtCore.QRect(50, 130, 81, 21))
        self.label_ID.setObjectName("label_ID")
        self.scrollArea_students = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_students.setGeometry(QtCore.QRect(300, 10, 281, 271))
        self.scrollArea_students.setWidgetResizable(True)
        self.scrollArea_students.setObjectName("scrollArea_students")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 279, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_students.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(10, 220, 91, 28))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_deleteall = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteall.setGeometry(QtCore.QRect(120, 220, 161, 28))
        self.pushButton_deleteall.setObjectName("pushButton_deleteall")
        delete_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(delete_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        delete_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(delete_2)
        self.statusbar.setObjectName("statusbar")
        delete_2.setStatusBar(self.statusbar)

        self.retranslateUi(delete_2)
        QtCore.QMetaObject.connectSlotsByName(delete_2)

    def retranslateUi(self, delete_2):
        _translate = QtCore.QCoreApplication.translate
        delete_2.setWindowTitle(_translate("delete_2", "MainWindow"))
        self.pushButton_search.setText(_translate("delete_2", "ყველა მონაცემი"))
        self.label_ID.setText(_translate("delete_2", "ID"))
        self.pushButton_delete.setText(_translate("delete_2", "წაშლა"))
        self.pushButton_deleteall.setText(_translate("delete_2", "ყველა ჩანაწერის წაშლა"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    delete_2 = QtWidgets.QMainWindow()
    ui = Ui_delete_2()
    ui.setupUi(delete_2)
    delete_2.show()
    sys.exit(app.exec_())
