# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_insert(object):
    def setupUi(self, insert):
        insert.setObjectName("insert")
        insert.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(insert)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(140, 40, 110, 21))
        self.label_name.setObjectName("label_name")
        self.label_surname = QtWidgets.QLabel(self.centralwidget)
        self.label_surname.setGeometry(QtCore.QRect(140, 80, 110, 21))
        self.label_surname.setObjectName("label_surname")
        self.label_age = QtWidgets.QLabel(self.centralwidget)
        self.label_age.setGeometry(QtCore.QRect(140, 130, 110, 21))
        self.label_age.setObjectName("label_age")
        self.label_gender = QtWidgets.QLabel(self.centralwidget)
        self.label_gender.setGeometry(QtCore.QRect(140, 180, 110, 21))
        self.label_gender.setObjectName("label_gender")
        self.label_grade = QtWidgets.QLabel(self.centralwidget)
        self.label_grade.setGeometry(QtCore.QRect(140, 230, 110, 21))
        self.label_grade.setObjectName("label_grade")
        self.pushButton_insert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_insert.setGeometry(QtCore.QRect(210, 280, 100, 28))
        self.pushButton_insert.setObjectName("pushButton_insert")
        self.label_insert_status = QtWidgets.QLabel(self.centralwidget)
        self.label_insert_status.setGeometry(QtCore.QRect(150, 320, 200, 16))
        self.label_insert_status.setText("")
        self.label_insert_status.setObjectName("label_insert_status")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(270, 40, 140, 22))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_surname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_surname.setGeometry(QtCore.QRect(270, 80, 140, 22))
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.comboBox_gender = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_gender.setGeometry(QtCore.QRect(270, 180, 100, 22))
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.spinBox_age = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_age.setGeometry(QtCore.QRect(270, 130, 60, 22))
        self.spinBox_age.setObjectName("spinBox_age")
        self.spinBox_grade = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_grade.setGeometry(QtCore.QRect(270, 230, 60, 22))
        self.spinBox_grade.setMaximum(100)
        self.spinBox_grade.setObjectName("spinBox_grade")
        insert.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(insert)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        insert.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(insert)
        self.statusbar.setObjectName("statusbar")
        insert.setStatusBar(self.statusbar)

        self.retranslateUi(insert)
        QtCore.QMetaObject.connectSlotsByName(insert)

    def retranslateUi(self, insert):
        _translate = QtCore.QCoreApplication.translate
        insert.setWindowTitle(_translate("insert", "MainWindow"))
        self.label_name.setText(_translate("insert", "სახელი"))
        self.label_surname.setText(_translate("insert", "გვარი"))
        self.label_age.setText(_translate("insert", "ასაკი"))
        self.label_gender.setText(_translate("insert", "გენდერი"))
        self.label_grade.setText(_translate("insert", "ნიშანი"))
        self.pushButton_insert.setText(_translate("insert", "ჩაწერე"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    insert = QtWidgets.QMainWindow()
    ui = Ui_insert()
    ui.setupUi(insert)
    insert.show()
    sys.exit(app.exec_())
