# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select(object):
    def setupUi(self, select):
        select.setObjectName("select")
        select.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(select)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 90, 16))
        self.label.setObjectName("label")
        self.comboBox_search_type = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_search_type.setGeometry(QtCore.QRect(40, 90, 100, 22))
        self.comboBox_search_type.setObjectName("comboBox_search_type")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(40, 190, 93, 28))
        self.pushButton_search.setObjectName("pushButton_search")
        self.scrollArea_students = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_students.setGeometry(QtCore.QRect(220, 60, 331, 271))
        self.scrollArea_students.setWidgetResizable(True)
        self.scrollArea_students.setObjectName("scrollArea_students")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 329, 269))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_students.setWidget(self.scrollAreaWidgetContents)
        self.label_students_list = QtWidgets.QLabel(self.centralwidget)
        self.label_students_list.setGeometry(QtCore.QRect(330, 30, 121, 20))
        self.label_students_list.setObjectName("label_students_list")
        self.lineEdit_search_by = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_search_by.setGeometry(QtCore.QRect(40, 140, 113, 22))
        self.lineEdit_search_by.setObjectName("lineEdit_search_by")
        select.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(select)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        select.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(select)
        self.statusbar.setObjectName("statusbar")
        select.setStatusBar(self.statusbar)

        self.retranslateUi(select)
        QtCore.QMetaObject.connectSlotsByName(select)

    def retranslateUi(self, select):
        _translate = QtCore.QCoreApplication.translate
        select.setWindowTitle(_translate("select", "MainWindow"))
        self.label.setText(_translate("select", "მოძებნეთ"))
        self.pushButton_search.setText(_translate("select", "ძებნა"))
        self.label_students_list.setText(_translate("select", "სტუდენტების სია"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    select = QtWidgets.QMainWindow()
    ui = Ui_select()
    ui.setupUi(select)
    select.show()
    sys.exit(app.exec_())
